# Variable 'location' was defined in the Variables tab
# Variable 'PrimaryDNSZone' was defined in the Variables tab
# Variable 'ResourceGroupName' was defined in the Variables tab
# Variable 'SPN' is defined in the Variables tab
trigger:
  branches:
    include:
    - refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - task: AzureCLI@2
    displayName: 'Azure CLI '
    inputs:
      connectedServiceNameARM: $(SPN)
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: >2-
         az group create --name $(ResourceGroupName) --location $(location)
                        az deployment group create  `
                        --template-file $(Build.SourcesDirectory)\Deploy-PublicDNS.bicep `
                        --resource-group $(ResourceGroupName) `
                        --parameters PrimaryDNSZone=$(PrimaryDNSZone)
      powerShellErrorActionPreference: continue
...
